name: CI

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller customtkinter pycryptodome pyperclip tkcalendar

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --collect-data customtkinter --hidden-import wmi --hidden-import pythoncom --name RSTao-Admin --icon assets/icon.ico admin_tool.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RSTao-Admin
          path: dist/RSTao-Admin.exe
